name: JS - Unit Tests

on: push

jobs:

  run-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          excluded_paths: "dist,node_modules"
          should_push: false
          artifact: "output-diagram.svg"
          output_file: "output-diagram.svg"
          path: ${{ steps.make_diagram.outputs.svg }}
    

      
          
 

          
