name: JS - Unit Tests

on: push

jobs:

  run-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          excluded_paths: "dist,node_modules"
      
  

      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.7.1     
        with:
          artifact_name: "mijn-diagram"
          should_push: false

          
 

          
